/// Convert a `snake_case` string to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Generate the content of a new migration file from a name.
///
/// Used by `reify new <name>`.
pub fn generate_migration_file(name: &str, version: &str) -> String {
    let struct_name = to_pascal_case(name);

    format!(
        r#"// Generated by: reify new {name}
use reify::{{Migration, MigrationContext}};

pub struct {struct_name};

impl Migration for {struct_name} {{
    fn version(&self) -> &'static str {{
        "{version}"
    }}

    fn description(&self) -> &'static str {{
        "{name}"
    }}

    // Optional: uncomment to attach a comment to the changelog entry.
    // fn comment(&self) -> Option<&'static str> {{
    //     Some("Describe the business reason or ticket reference here.")
    // }}

    fn up(&self, ctx: &mut MigrationContext) {{
        todo!("implement up migration")
    }}

    fn down(&self, ctx: &mut MigrationContext) {{
        todo!("implement down migration")
    }}
}}
"#
    )
}

/// Generate the content of a new **view** migration file from a name.
///
/// Used by `reify new --view <name>`.
pub fn generate_view_migration_file(name: &str, version: &str) -> String {
    let struct_name = to_pascal_case(name);

    format!(
        r#"// Generated by: reify new --view {name}
use reify::{{Migration, MigrationContext}};

pub struct {struct_name};

impl Migration for {struct_name} {{
    fn version(&self) -> &'static str {{
        "{version}"
    }}

    fn description(&self) -> &'static str {{
        "Create view {name}"
    }}

    // Optional: uncomment to attach a comment to the changelog entry.
    // fn comment(&self) -> Option<&'static str> {{
    //     Some("Describe the business reason or ticket reference here.")
    // }}

    fn up(&self, ctx: &mut MigrationContext) {{
        ctx.create_view("{name}", "SELECT ... FROM ... WHERE ...");
    }}

    fn down(&self, ctx: &mut MigrationContext) {{
        ctx.drop_view("{name}");
    }}
}}
"#
    )
}

/// Generate the content of a new **materialized view** migration file from a name.
///
/// Used by `reify new --materialized-view <name>`.
pub fn generate_materialized_view_migration_file(name: &str, version: &str) -> String {
    let struct_name = to_pascal_case(name);

    format!(
        r#"// Generated by: reify new --materialized-view {name}
use reify::{{Migration, MigrationContext}};

pub struct {struct_name};

impl Migration for {struct_name} {{
    fn version(&self) -> &'static str {{
        "{version}"
    }}

    fn description(&self) -> &'static str {{
        "Create materialized view {name}"
    }}

    // Optional: uncomment to attach a comment to the changelog entry.
    // fn comment(&self) -> Option<&'static str> {{
    //     Some("Describe the business reason or ticket reference here.")
    // }}

    fn up(&self, ctx: &mut MigrationContext) {{
        ctx.create_materialized_view("{name}", "SELECT ... FROM ... WHERE ...");
    }}

    fn down(&self, ctx: &mut MigrationContext) {{
        ctx.drop_materialized_view("{name}");
    }}
}}
"#
    )
}
