use super::context::MigrationContext;
use super::traits::Migration;

/// Generate the content of a new migration file from a name.
///
/// Used by `reify new <name>`.
pub fn generate_migration_file(name: &str, version: &str) -> String {
    // Convert snake_case name to PascalCase struct name
    let struct_name: String = name
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect();

    format!(
        r#"// Generated by: reify new {name}
use reify::{{Migration, MigrationContext}};

pub struct {struct_name};

impl Migration for {struct_name} {{
    fn version(&self) -> &'static str {{
        "{version}"
    }}

    fn description(&self) -> &'static str {{
        "{name}"
    }}

    fn up(&self, ctx: &mut MigrationContext) {{
        todo!("implement up migration")
    }}

    fn down(&self, ctx: &mut MigrationContext) {{
        todo!("implement down migration")
    }}
}}
"#
    )
}

/// Generate the content of a new **view** migration file from a name.
///
/// Used by `reify new --view <name>`.
pub fn generate_view_migration_file(name: &str, version: &str) -> String {
    let struct_name: String = name
        .split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect();

    format!(
        r#"// Generated by: reify new --view {name}
use reify::{{Migration, MigrationContext}};

pub struct {struct_name};

impl Migration for {struct_name} {{
    fn version(&self) -> &'static str {{
        "{version}"
    }}

    fn description(&self) -> &'static str {{
        "Create view {name}"
    }}

    fn up(&self, ctx: &mut MigrationContext) {{
        ctx.create_view("{name}", "SELECT ... FROM ... WHERE ...");
    }}

    fn down(&self, ctx: &mut MigrationContext) {{
        ctx.drop_view("{name}");
    }}
}}
"#
    )
}
