use crate::ident::qi;
use crate::table::Table;

/// Generate a `CREATE TABLE IF NOT EXISTS` statement for a `Table` type.
///
/// Column types and constraints are read from the provided `ColumnDef` metadata
/// (generated by `#[derive(Table)]` or the `Schema` builder API).
/// The `dialect` controls backend-specific type rendering.
pub fn create_table_sql<T: Table>(
    column_defs: &[crate::schema::ColumnDef],
    dialect: crate::query::Dialect,
) -> String {
    use crate::schema::{ComputedColumn, TimestampKind, TimestampSource};

    let table = T::table_name();
    let names = T::column_names();

    let mut col_lines: Vec<String> = Vec::new();

    for name in names.iter() {
        let def = column_defs.iter().find(|d| d.name == *name);

        // Skip Rust-side virtual columns — they don't exist in the DB.
        if let Some(d) = def {
            if matches!(d.computed, Some(ComputedColumn::Virtual)) {
                continue;
            }
        }

        let mut parts: Vec<String> = vec![format!("    {}", qi(name))];

        let is_nullable = def.map(|d| d.nullable).unwrap_or(false);
        let is_pk = def.map(|d| d.primary_key).unwrap_or(false);
        let is_unique = def.map(|d| d.unique).unwrap_or(false);
        let default_val = def.and_then(|d| d.default.as_deref());
        let computed = def.and_then(|d| d.computed.as_ref());
        let ts_kind = def.and_then(|d| d.timestamp_kind);
        let ts_source = def
            .map(|d| d.timestamp_source)
            .unwrap_or(TimestampSource::Vm);

        // Type — from metadata, not from column name heuristics
        let sql_type = def
            .map(|d| d.sql_type.to_sql(dialect))
            .unwrap_or(std::borrow::Cow::Borrowed("TEXT"));
        parts.push(sql_type.into_owned());

        // DB-generated computed column: GENERATED ALWAYS AS (expr) STORED
        if let Some(ComputedColumn::Stored(expr)) = computed {
            parts.push(format!("GENERATED ALWAYS AS ({expr}) STORED"));
        } else {
            // Constraints (not applicable to generated columns)
            if is_pk {
                parts.push("PRIMARY KEY".into());
            }
            if !is_nullable && !is_pk {
                parts.push("NOT NULL".into());
            }
            if is_unique {
                parts.push("UNIQUE".into());
            }

            // DB-source timestamps: emit dialect-appropriate DEFAULT
            if ts_source == TimestampSource::Db && ts_kind.is_some() {
                let default_now = match dialect {
                    crate::query::Dialect::Mysql => "DEFAULT CURRENT_TIMESTAMP",
                    _ => "DEFAULT NOW()",
                };
                parts.push(default_now.into());

                // MySQL: update_timestamp with Db source gets ON UPDATE CURRENT_TIMESTAMP
                if ts_kind == Some(TimestampKind::Update) && dialect == crate::query::Dialect::Mysql
                {
                    parts.push("ON UPDATE CURRENT_TIMESTAMP".into());
                }
            } else if let Some(dv) = default_val {
                parts.push(format!("DEFAULT {dv}"));
            }

            // Column-level CHECK constraint
            if let Some(check_expr) = def.and_then(|d| d.check.as_deref()) {
                parts.push(format!("CHECK ({check_expr})"));
            }
        }

        col_lines.push(parts.join(" "));
    }

    // Append FOREIGN KEY constraints as table-level lines
    let fk_lines: Vec<String> = names
        .iter()
        .filter_map(|name| {
            let def = column_defs.iter().find(|d| d.name == *name)?;
            let fk = def.foreign_key.as_ref()?;
            Some(format!(
                "    FOREIGN KEY ({}) {}",
                qi(name),
                fk.to_references_clause()
            ))
        })
        .collect();

    if fk_lines.is_empty() {
        format!(
            "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
            qi(table),
            col_lines.join(",\n")
        )
    } else {
        format!(
            "CREATE TABLE IF NOT EXISTS {} (\n{},\n{}\n);",
            qi(table),
            col_lines.join(",\n"),
            fk_lines.join(",\n")
        )
    }
}

/// Generate a `CREATE TABLE IF NOT EXISTS` statement with optional table-level
/// CHECK constraints (from `TableSchema.checks`).
///
/// Column-level CHECK constraints are rendered inline by `create_table_sql`;
/// this function additionally appends table-level CHECK lines after all columns.
pub fn create_table_sql_with_checks<T: Table>(
    column_defs: &[crate::schema::ColumnDef],
    checks: &[String],
    dialect: crate::query::Dialect,
) -> String {
    if checks.is_empty() {
        return create_table_sql::<T>(column_defs, dialect);
    }

    // Build the base DDL (without the closing ");") and append table-level checks
    let base = create_table_sql::<T>(column_defs, dialect);
    // Strip trailing "\n);" to append more lines
    let trimmed = base.trim_end_matches("\n);");
    let mut result = trimmed.to_string();
    for check in checks {
        result.push_str(&format!(",\n    CHECK ({check})"));
    }
    result.push_str("\n);");
    result
}

/// Generate a `CREATE TABLE IF NOT EXISTS` statement from an explicit table name
/// and column definitions (used for synthetic tables like audit companions).
pub(crate) fn create_table_sql_named(
    table_name: &str,
    column_defs: &[crate::schema::ColumnDef],
    dialect: crate::query::Dialect,
) -> String {
    use crate::schema::TimestampSource;

    let mut col_lines: Vec<String> = Vec::new();

    for def in column_defs {
        let mut parts: Vec<String> = vec![format!("    {}", qi(def.name))];

        let sql_type = def.sql_type.to_sql(dialect);
        parts.push(sql_type.into_owned());

        if def.primary_key {
            parts.push("PRIMARY KEY".into());
        }
        if !def.nullable && !def.primary_key {
            parts.push("NOT NULL".into());
        }
        if def.unique {
            parts.push("UNIQUE".into());
        }
        if def.timestamp_source == TimestampSource::Db {
            let default_now = match dialect {
                crate::query::Dialect::Mysql => "DEFAULT CURRENT_TIMESTAMP",
                _ => "DEFAULT NOW()",
            };
            parts.push(default_now.into());
        } else if let Some(ref dv) = def.default {
            parts.push(format!("DEFAULT {dv}"));
        }

        // Column-level CHECK constraint
        if let Some(ref check_expr) = def.check {
            parts.push(format!("CHECK ({check_expr})"));
        }

        col_lines.push(parts.join(" "));
    }

    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
        qi(table_name),
        col_lines.join(",\n")
    )
}

/// Error returned by [`try_add_column_sql`] when a NOT NULL column is added
/// without a default the engine can safely synthesise.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MissingDefaultError {
    pub table: String,
    pub column: String,
    pub sql_type: String,
}

impl std::fmt::Display for MissingDefaultError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "cannot ADD COLUMN {:?}.{:?} ({}) NOT NULL without an explicit `default` — no safe fallback exists for this type; set `default = \"…\"` on the column or make it nullable",
            self.table, self.column, self.sql_type
        )
    }
}

impl std::error::Error for MissingDefaultError {}

/// Generate `ALTER TABLE … ADD COLUMN` for columns present in the struct
/// but missing from the database.
///
/// Panics if the column is NOT NULL and no default can be synthesised. Use
/// [`try_add_column_sql`] for a recoverable variant — the CLI calls it so
/// the error surfaces before anything is written.
pub fn add_column_sql(
    table: &str,
    column: &str,
    def: Option<&crate::schema::ColumnDef>,
    dialect: crate::query::Dialect,
) -> String {
    try_add_column_sql(table, column, def, dialect).unwrap_or_else(|e| panic!("{e}"))
}

/// Fallible variant of [`add_column_sql`]. Returns [`MissingDefaultError`]
/// when a NOT NULL column is added without an explicit default and the type
/// has no safe fallback (UUID, JSONB, BYTEA, arrays, custom types), so the
/// caller can surface a clear error before the DDL is executed.
pub fn try_add_column_sql(
    table: &str,
    column: &str,
    def: Option<&crate::schema::ColumnDef>,
    dialect: crate::query::Dialect,
) -> Result<String, MissingDefaultError> {
    use crate::schema::ComputedColumn;

    // DB-generated computed column
    if let Some(d) = def {
        if let Some(ComputedColumn::Stored(expr)) = &d.computed {
            let sql_type = d.sql_type.to_sql(dialect);
            return Ok(format!(
                "ALTER TABLE {} ADD COLUMN {} {} GENERATED ALWAYS AS ({expr}) STORED;",
                qi(table),
                qi(column),
                &*sql_type
            ));
        }
    }

    let is_nullable = def.map(|d| d.nullable).unwrap_or(false);
    let sql_type = def
        .map(|d| d.sql_type.to_sql(dialect))
        .unwrap_or(std::borrow::Cow::Borrowed("TEXT"));
    let null_clause = if is_nullable { "" } else { " NOT NULL" };
    // For NOT NULL columns, emit a DEFAULT so existing rows don't violate the
    // constraint. Prefer an explicit ColumnDef default; otherwise fall back
    // to a type-inferred safe default. For types where no safe default exists
    // (UUID, JSONB, BYTEA, …) we refuse to generate the DDL — silently
    // emitting `ADD COLUMN … NOT NULL` with no default would have the
    // database reject the migration at execution time with a less helpful
    // error.
    let default_clause = if is_nullable {
        String::new()
    } else {
        let explicit = def.and_then(|d| d.default.as_deref());
        match explicit {
            Some(dv) => format!(" DEFAULT {dv}"),
            None => match default_for_type(&sql_type) {
                Some(dv) => format!(" DEFAULT {dv}"),
                None => {
                    return Err(MissingDefaultError {
                        table: table.to_string(),
                        column: column.to_string(),
                        sql_type: sql_type.into_owned(),
                    });
                }
            },
        }
    };
    Ok(format!(
        "ALTER TABLE {} ADD COLUMN {} {sql_type}{null_clause}{default_clause};",
        qi(table),
        qi(column)
    ))
}

/// Return a safe SQL literal to use as a `DEFAULT` when adding a NOT NULL column
/// to an existing table.
///
/// Returns `None` for types where no universally safe default exists (e.g. `UUID`,
/// `JSONB`, `BYTEA`). In that case the caller must supply an explicit `default` in
/// the `ColumnDef`, or the database will reject the `ALTER TABLE`.
fn default_for_type(ty: &str) -> Option<&'static str> {
    let upper = ty.to_uppercase();
    if upper.starts_with("DECIMAL") || upper.starts_with("NUMERIC") {
        return Some("0");
    }
    if upper.starts_with("VARCHAR") || upper.starts_with("CHAR(") {
        return Some("''");
    }
    match upper.as_str() {
        "BIGINT" | "INTEGER" | "SMALLINT" | "BIGSERIAL" | "SERIAL" | "INT" | "INT2" | "INT4"
        | "INT8" => Some("0"),
        "REAL" | "FLOAT4" | "FLOAT8" | "DOUBLE PRECISION" => Some("0"),
        "BOOLEAN" | "BOOL" => Some("FALSE"),
        "TEXT" => Some("''"),
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => Some("NOW()"),
        // UUID, JSONB, BYTEA, arrays, custom types — no safe default
        _ => None,
    }
}
