use crate::ident::qi;
use crate::table::Table;

/// Generate a `CREATE TABLE IF NOT EXISTS` statement for a `Table` type.
///
/// Column types and constraints are read from the provided `ColumnDef` metadata
/// (generated by `#[derive(Table)]` or the `Schema` builder API).
/// The `dialect` controls backend-specific type rendering.
pub fn create_table_sql<T: Table>(
    column_defs: &[crate::schema::ColumnDef],
    dialect: crate::query::Dialect,
) -> String {
    use crate::schema::{ComputedColumn, TimestampKind, TimestampSource};

    let table = T::table_name();
    let names = T::column_names();

    let mut col_lines: Vec<String> = Vec::new();

    for name in names.iter() {
        let def = column_defs.iter().find(|d| d.name == *name);

        // Skip Rust-side virtual columns — they don't exist in the DB.
        if let Some(d) = def {
            if matches!(d.computed, Some(ComputedColumn::Virtual)) {
                continue;
            }
        }

        let mut parts: Vec<String> = vec![format!("    {}", qi(name))];

        let is_nullable = def.map(|d| d.nullable).unwrap_or(false);
        let is_pk = def.map(|d| d.primary_key).unwrap_or(false);
        let is_unique = def.map(|d| d.unique).unwrap_or(false);
        let default_val = def.and_then(|d| d.default.as_deref());
        let computed = def.and_then(|d| d.computed.as_ref());
        let ts_kind = def.and_then(|d| d.timestamp_kind);
        let ts_source = def
            .map(|d| d.timestamp_source)
            .unwrap_or(TimestampSource::Vm);

        // Type — from metadata, not from column name heuristics
        let sql_type = def
            .map(|d| d.sql_type.to_sql(dialect))
            .unwrap_or(std::borrow::Cow::Borrowed("TEXT"));
        parts.push(sql_type.into_owned());

        // DB-generated computed column: GENERATED ALWAYS AS (expr) STORED
        if let Some(ComputedColumn::Stored(expr)) = computed {
            parts.push(format!("GENERATED ALWAYS AS ({expr}) STORED"));
        } else {
            // Constraints (not applicable to generated columns)
            if is_pk {
                parts.push("PRIMARY KEY".into());
            }
            if !is_nullable && !is_pk {
                parts.push("NOT NULL".into());
            }
            if is_unique {
                parts.push("UNIQUE".into());
            }

            // DB-source timestamps: emit dialect-appropriate DEFAULT
            if ts_source == TimestampSource::Db && ts_kind.is_some() {
                let default_now = match dialect {
                    crate::query::Dialect::Mysql => "DEFAULT CURRENT_TIMESTAMP",
                    _ => "DEFAULT NOW()",
                };
                parts.push(default_now.into());

                // MySQL: update_timestamp with Db source gets ON UPDATE CURRENT_TIMESTAMP
                if ts_kind == Some(TimestampKind::Update) && dialect == crate::query::Dialect::Mysql
                {
                    parts.push("ON UPDATE CURRENT_TIMESTAMP".into());
                }
            } else if let Some(dv) = default_val {
                parts.push(format!("DEFAULT {dv}"));
            }

            // Column-level CHECK constraint
            if let Some(check_expr) = def.and_then(|d| d.check.as_deref()) {
                parts.push(format!("CHECK ({check_expr})"));
            }
        }

        col_lines.push(parts.join(" "));
    }

    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
        qi(table),
        col_lines.join(",\n")
    )
}

/// Generate a `CREATE TABLE IF NOT EXISTS` statement with optional table-level
/// CHECK constraints (from `TableSchema.checks`).
///
/// Column-level CHECK constraints are rendered inline by `create_table_sql`;
/// this function additionally appends table-level CHECK lines after all columns.
pub fn create_table_sql_with_checks<T: Table>(
    column_defs: &[crate::schema::ColumnDef],
    checks: &[String],
    dialect: crate::query::Dialect,
) -> String {
    if checks.is_empty() {
        return create_table_sql::<T>(column_defs, dialect);
    }

    // Build the base DDL (without the closing ");") and append table-level checks
    let base = create_table_sql::<T>(column_defs, dialect);
    // Strip trailing "\n);" to append more lines
    let trimmed = base.trim_end_matches("\n);");
    let mut result = trimmed.to_string();
    for check in checks {
        result.push_str(&format!(",\n    CHECK ({check})"));
    }
    result.push_str("\n);");
    result
}

/// Generate a `CREATE TABLE IF NOT EXISTS` statement from an explicit table name
/// and column definitions (used for synthetic tables like audit companions).
pub(crate) fn create_table_sql_named(
    table_name: &str,
    column_defs: &[crate::schema::ColumnDef],
    dialect: crate::query::Dialect,
) -> String {
    use crate::schema::TimestampSource;

    let mut col_lines: Vec<String> = Vec::new();

    for def in column_defs {
        let mut parts: Vec<String> = vec![format!("    {}", qi(def.name))];

        let sql_type = def.sql_type.to_sql(dialect);
        parts.push(sql_type.into_owned());

        if def.primary_key {
            parts.push("PRIMARY KEY".into());
        }
        if !def.nullable && !def.primary_key {
            parts.push("NOT NULL".into());
        }
        if def.unique {
            parts.push("UNIQUE".into());
        }
        if def.timestamp_source == TimestampSource::Db {
            let default_now = match dialect {
                crate::query::Dialect::Mysql => "DEFAULT CURRENT_TIMESTAMP",
                _ => "DEFAULT NOW()",
            };
            parts.push(default_now.into());
        } else if let Some(ref dv) = def.default {
            parts.push(format!("DEFAULT {dv}"));
        }

        // Column-level CHECK constraint
        if let Some(ref check_expr) = def.check {
            parts.push(format!("CHECK ({check_expr})"));
        }

        col_lines.push(parts.join(" "));
    }

    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
        qi(table_name),
        col_lines.join(",\n")
    )
}

/// Generate `ALTER TABLE … ADD COLUMN` for columns present in the struct
/// but missing from the database.
pub fn add_column_sql(
    table: &str,
    column: &str,
    def: Option<&crate::schema::ColumnDef>,
    dialect: crate::query::Dialect,
) -> String {
    use crate::schema::ComputedColumn;

    // DB-generated computed column
    if let Some(d) = def {
        if let Some(ComputedColumn::Stored(expr)) = &d.computed {
            let sql_type = d.sql_type.to_sql(dialect);
            return format!(
                "ALTER TABLE {} ADD COLUMN {} {} GENERATED ALWAYS AS ({expr}) STORED;",
                qi(table),
                qi(column),
                &*sql_type
            );
        }
    }

    let is_nullable = def.map(|d| d.nullable).unwrap_or(false);
    let sql_type = def
        .map(|d| d.sql_type.to_sql(dialect))
        .unwrap_or(std::borrow::Cow::Borrowed("TEXT"));
    let null_clause = if is_nullable { "" } else { " NOT NULL" };
    let default_clause = if !is_nullable {
        format!(" DEFAULT {}", default_for_type(&sql_type))
    } else {
        String::new()
    };
    format!(
        "ALTER TABLE {} ADD COLUMN {} {sql_type}{null_clause}{default_clause};",
        qi(table),
        qi(column)
    )
}

fn default_for_type(ty: &str) -> &'static str {
    if ty.starts_with("DECIMAL") || ty.starts_with("NUMERIC") {
        return "0";
    }
    if ty.starts_with("VARCHAR") || ty.starts_with("CHAR(") {
        return "''";
    }
    match ty {
        "BIGINT" | "INTEGER" | "SMALLINT" | "NUMERIC" | "BIGSERIAL" | "SERIAL" => "0",
        "BOOLEAN" => "FALSE",
        "TIMESTAMPTZ" | "TIMESTAMP" | "DATETIME" => "NOW()",
        _ => "''",
    }
}
