use std::marker::PhantomData;

use crate::table::Table;

// ── RelationType ─────────────────────────────────────────────────────

/// Cardinality / direction of a relation between two tables.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelationType {
    /// One parent row → many child rows (`users` → `posts`).\
    /// The foreign key lives on the **child** table.
    HasMany,
    /// One parent row → at most one child row (`users` → `profiles`).\
    /// The foreign key lives on the **child** table.
    HasOne,
    /// This table holds the foreign key pointing to the parent
    /// (`posts.user_id` → `users.id`).
    BelongsTo,
}

// ── Relation ─────────────────────────────────────────────────────────

/// A typed, named relation from table `F` to table `T`.
///
/// Instances are returned by the methods generated by `#[relations(...)]`
/// and consumed by `SelectBuilder::join` / `SelectBuilder::with`.
///
/// ```ignore
/// // Generated by #[relations(has_many(posts: Post, foreign_key = "user_id"))]
/// let rel: Relation<User, Post> = User::posts();
/// assert_eq!(rel.rel_type, RelationType::HasMany);
/// assert_eq!(rel.from_col, "id");
/// assert_eq!(rel.to_col,   "user_id");
/// ```
#[derive(Debug, Clone)]
pub struct Relation<F: Table, T: Table> {
    /// Human-readable name of the relation (e.g. `"posts"`).
    pub name: &'static str,
    /// Cardinality / direction.
    pub rel_type: RelationType,
    /// Column on the **`F`** side of the join.
    pub from_col: &'static str,
    /// Column on the **`T`** side of the join.
    pub to_col: &'static str,
    _from: PhantomData<F>,
    _to: PhantomData<T>,
}

impl<F: Table, T: Table> Relation<F, T> {
    /// Construct a relation descriptor.
    ///
    /// Prefer the generated factory methods (`User::posts()`, etc.) over
    /// calling this directly.
    pub const fn new(
        name: &'static str,
        rel_type: RelationType,
        from_col: &'static str,
        to_col: &'static str,
    ) -> Self {
        Self {
            name,
            rel_type,
            from_col,
            to_col,
            _from: PhantomData,
            _to: PhantomData,
        }
    }

    /// SQL JOIN condition fragment: `"from_table.from_col = to_table.to_col"`.
    pub fn join_condition(&self) -> String {
        format!(
            "{}.{} = {}.{}",
            F::table_name(),
            self.from_col,
            T::table_name(),
            self.to_col,
        )
    }
}

// ── Related trait ────────────────────────────────────────────────────

/// Optional trait for tables that declare a canonical relation to `T`.
///
/// Implement this when you want a single default relation between two
/// tables that can be used without specifying columns explicitly.
///
/// ```ignore
/// impl Related<Post> for User {
///     fn relation() -> Relation<Self, Post> {
///         User::posts()
///     }
/// }
/// ```
pub trait Related<T: Table>: Table {
    fn relation() -> Relation<Self, T>;
}
