use crate::value::Value;

/// Trait implemented by `#[derive(Table)]` on user structs.
///
/// Covers row serialisation/deserialisation and query builder wiring.
/// Schema DDL (column types, constraints, indexes) is defined separately
/// via [`crate::schema::Schema`].
pub trait Table: Sized {
    /// SQL table name.
    fn table_name() -> &'static str;

    /// Ordered list of column names (matches struct field order).
    fn column_names() -> &'static [&'static str];

    /// Convert this instance into a list of `Value`s (same order as `column_names`).
    fn into_values(&self) -> Vec<Value>;

    /// Column names that are writable (excludes computed and DB-managed timestamp columns).
    ///
    /// Generated by `#[derive(Table)]` from `#[column(primary_key, auto_increment,
    /// computed_rust, timestamp_source = "db")]` annotations.
    /// Falls back to all column names when not overridden.
    fn writable_column_names() -> Vec<&'static str> {
        Self::column_names().to_vec()
    }

    /// Values for writable columns only (excludes computed and DB-managed timestamp columns).
    ///
    /// Pairs with `writable_column_names()` — same order, same length.
    fn writable_values(&self) -> Vec<Value> {
        self.into_values()
    }

    /// Column names marked as `update_timestamp` with application-side (`Vm`) source.
    ///
    /// Used by `UpdateBuilder` to auto-inject `SET col = NOW()` on every UPDATE.
    /// Returns an empty vec when no update-timestamp columns exist.
    fn update_timestamp_columns() -> Vec<&'static str> {
        vec![]
    }

    /// Column names that exist in the database (excludes `computed_rust` virtual columns).
    ///
    /// Includes DB-generated computed columns (they exist in the schema) but
    /// excludes Rust-side virtual columns (they don't exist in the DB at all).
    fn db_column_names() -> Vec<&'static str> {
        Self::column_names().to_vec()
    }
}
